Move logout button
codeforpdx/dwellingly-app pull request #175
Opened 2020-05-09 08:05 UTC by wrunion

I wrote this in the convo too, but I moved the logout button into the Header component, so it's now on top. I don't know SASS yet though, and I couldn't get it to the right. 

It seems it's where it needs to be now though, component-wise, and I made a note of where the new CSS rules need to go. I'll read up on Burma and SASS, but I wanted to get this request moving along, and see if anyone else knows which rules are affecting which components, and how to override them for this.

Alright!

2020-05-09 08:10 UTC, chrisandrewca submitted a review, later dismissed
Looks great!

2020-05-13 05:47 UTC, Chris-Boe commented
It looks like you started this branch off your old `winter` branch, which still had the changes to the /stashed folder. While it's no big deal here, remember to always start off from development when you can!

2020-05-13 05:54 UTC, Chris-Boe requested changes

2020-05-13 05:54 UTC, Chris-Boe commented on src/scss/helpers.scss
> +  /* TO DO: create a rule to move button to the top right */
Let me know if you need help with the CSS for this! I have an example

2020-06-11 03:26 UTC, Chris-Boe commented
Thanks for your work Winter, Darren got this finished up while you are away.
Hope to see you again soon and hope you are staying healthy and safe!

2020-06-11 03:26 UTC, closed without merging