Integrate tenants to dashboard
codeforpdx/dwellingly-app pull request #176
Opened 2020-05-13 04:00 UTC by DaveTrost

addressing issue #174 

- [x] get a list of the tenants who have no staff assignments. GET from /tenants and those tenants without an assigned staff member will have `staff: None` in their JSON data
- [x] get a list of the JOIN staff members for assignment. POST to /users/role and include the following JSON object in the body: "userrole": "admin".
- [x] when the "Save Assignments" button is clicked, for each tenant whose staff assignment has been updated, send a PUT request to /tenants/<tenantID> and with a JSON body as follows: staffIDs: [<staffID from the staff members list>]
- [x] after the "Save Assignments" button is clicked, remove those tenants from the list who now have been given staff assignments

2020-05-13 17:34 UTC, Chris-Boe requested changes
Looks great! Just the one change and some merge conflicts

2020-05-13 17:34 UTC, Chris-Boe commented on src/views/dashboard.js
> +          .post(`${process.env.REACT_APP_API_URL}/users/role`, data, makeAuthHeaders(session))
Since I don't see this data being used anywhere except in the dropdown to assign tenants, we could put this behind a conditional inside the "then" of the /tenants call above, so that we only call it if we have tenants that need staff assignment

2020-05-13 21:23 UTC, DaveTrost commented on src/views/dashboard.js
> +          .post(`${process.env.REACT_APP_API_URL}/users/role`, data, makeAuthHeaders(session))
Good catch. I also had a non-empty dependency list in my useEffect and so the API calls were running twice on first load. I fixed this using a pattern called useMountEffect that I found on stack overflow

2020-05-13 21:26 UTC, DaveTrost commented
All issues noted in reviews should be handled now. Please take a look

2020-05-21 02:17 UTC, Chris-Boe approved these changes

2020-05-21 02:17 UTC, merged