Move logout btn
codeforpdx/dwellingly-app pull request #188
Opened 2020-05-28 03:25 UTC by dbridenbeck

### Purpose
* move logout button to top-right of view
* remove logout button from sidebar

### Validating
* logout button should appear in header
* while on /dashboard it logout button should be right-aligned with the tile below it, “New Property Managers”
* clicking the logout buttons should log a user out

### Follow-on questions
* I moved LogOutButton into it’s own component. Is it preferred that I keep it in Header.js instead?

2020-05-28 03:46 UTC, Chris-Boe requested changes
Looks like this was branched off Michael's Footer update PR when he had a commit that changed a lot of unrelated files, so make sure you branch off most recent development and then make your changes :)
You can do this with a rebase and drop the first two commits. Let me know if you have any questions!

2020-05-30 21:59 UTC, dbridenbeck commented
Hi @Chris-Boe! I just rebased and re-pushed it (had to do a force push, which makes sense, right?)

This is my first time rebasing, so please let me know if there's anything that looks amiss. And thanks for the helpful reminder re: always branching off of the most recent development, and not other branches!

2020-06-06 07:22 UTC, Chris-Boe submitted a review, later dismissed
Just need to fix merge conflicts. Looks good!

2020-06-11 03:24 UTC, Chris-Boe approved these changes

2020-06-11 03:24 UTC, merged