Toast notifications
codeforpdx/dwellingly-app pull request #323
Opened 2020-09-12 20:47 UTC by yhafez

### What issue is this solving?
Please connect this Pull Request to the issue it is resolving by using the controls on the right side of this PR.
Resolves #264

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? Yes, I've added the "react-toastify" package
Any special requirements to test? I haven't run into issues on my machine, but just play around with various submission forms throughout the website, and confirm that notifications pop-up as toast notification in the bottom right

This has NOT been tested for mobile

Two commits are included. The first is the implementation of toast notifications, the second is readme changes to contributing.md about how to add toast notifications.

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code
- [x] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

2020-09-12 20:56 UTC, yhafez commented on src/App.js
> +                {this.state.userSession.isAuthenticated
Ah, so aside from adding the "ToastContainer" here, I cleaned up the indentation which is why there's some changes here.

2020-10-03 22:27 UTC, Chris-Boe requested changes
This looks great! We might want to verify the bottom-right placement with Michelle because it seems a bit too out of the way but I love the look and the animation!
Just the one comment on the documentation and some merge conflicts

2020-10-03 22:27 UTC, Chris-Boe commented on contributing.md
> +## Adding user notifications
I think we can move this section to the new common components doc!

2020-11-11 21:01 UTC, yhafez commented on src/App.js
> +            position="bottom-right"
@Chris-Boe, if we decide to change the position from the bottom-right, it's as easy as  changing this attribute right here!

2020-11-12 04:05 UTC, Chris-Boe approved these changes

2020-11-12 04:05 UTC, merged