Add forgot password page
codeforpdx/dwellingly-app pull request #341
Opened 2020-09-15 21:49 UTC by dbridenbeck

### What issue is this solving?
Closes #132 

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary?: Nope!
Any special requirements to test?: Yes, you need to add this to app.py on the backend to suppress sending any actual emails when submitting the form on the Forgot Password page:

```
app.config['MAIL_SUPPRESS_SEND'] = True
```

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code
- [x] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

2020-09-15 23:22 UTC, NickSchimek commented
@dbridenbeck It may be good to commit this change `app.config['MAIL_SUPPRESS_SEND'] = True` as the default config for now with this PR so that the app doesn't appear broken to other devs who may want to play with this endpoint. Issue #307 will take care of this issue, but until it is done it might be good to set it as true for now.

2020-09-16 03:34 UTC, NickSchimek commented
I tested live and this works. There are some improvements that can be done in the backend to improve the UX on the frontend. For example: sending emails in either a background job or asynchronously to eliminate the lag a user sees when they click submit on the form. <- I plan to eventually create a ticket for this.

As far as I can see this implements half of the reset password functionality. I'm not sure if there is another issue to implement the other half. If not, it will need to be created to implement the functionality when a user clicks on the link in the email - they should be taken to a page that allows them to reset their password. (Note: Current URL's set in the backend email template will need to be updated to whatever URL the frontend requires).

We will need to decide wether or not we want to automatically log the user in when resetting their password or not.

2020-10-04 16:02 UTC, Chris-Boe requested changes
Looks great! Just needs to be rebased and have the merge conflicts resolved. Let's also add the modal component to the reusable docs if it's ready!

2020-10-04 16:02 UTC, Chris-Boe commented on src/scss/pages/_dashboard.scss
> +// .modal {
Let's delete these since we aren't using them anymore

2020-10-04 16:02 UTC, Chris-Boe commented on src/views/dashboard.js
> +            {/* TODO replace this with our modal! Marie and Darren are smart :) */}
😆

2020-10-07 14:47 UTC, dbridenbeck commented
Just pushed up my changes, and also added PropTypes to the Modal component. 

Note that I tried testing this again but upon trying to pull down the backend I ran into issues and am unable to get the backend running anymore :( 

Any chance you could test this in the UI again? I know a lot of work has been done in the backend recently and it might be worth double-triple checking that the forgot password page is still working.

2020-10-08 14:48 UTC, dbridenbeck commented
Alright, I resolved the merge conflicts and had to do some tinkering with the logic on the dashboard for opening/closing the modal, along with some CSS to ensure that the buttons had some better spacing between each other when hasButtons = true for the Modal component.

I tested this by setting SUPPRESS_MAIL_SEND to 'true' in config.py and all is working well. My main concern here is the heavy amount of merge commits I had to fight through, so another set of eyes on this would be helpful!

2020-10-09 15:44 UTC, Chris-Boe approved these changes
Looks good!

2020-10-09 15:44 UTC, merged