Css clean up
codeforpdx/dwellingly-app pull request #371
Opened 2020-09-24 19:27 UTC by SeHarlan

### What issue is this solving?
#343 stage one
I've made all the buttons I could find have bulma classnames. Bulma has overrides we can use so if we want to change the hover behavior in all of our buttons we only need to implement this variable in the variables page, $button-text-hover-color.

most hard coded colors I found were changed to variables so they can all be changed from one place.

Next steps are to clean up the code I've commented out and figure out the best way to organize the CSS that we do want to keep, which I try and keep to just structural stuff.

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? Bulma version has been upgraded to 9.0 so I believe so
Any special requirements to test?

### Please make sure you've attempted to meet the following coding standards
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code
- [ ] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

2020-09-25 09:13 UTC, beekman submitted a review, later dismissed
Looks good, nice job cleaning up and converting to bulma ui standards. Hopefully we can clean up the comments soon, as things won't actually be all that much cleaner until those comments are relegated to  git history.

2020-09-26 12:00 UTC, beekman commented
I went ahead and took the leap to a single scss file, main.scss. Moved all scss from other files to replace their import statements. If this wasn't the intent, we can always revert the commits.

2020-09-26 12:01 UTC, beekman approved these changes

2020-10-03 21:42 UTC, Chris-Boe requested changes
If these style changes are good and permanent, I think we should delete all the commented out CSS

2020-10-03 21:42 UTC, Chris-Boe commented on src/components/Button/button.scss
> +// .styled-button {
The reference to the deleted `variables.scss` above needs to be deleted to be able to run the app

2020-10-08 02:19 UTC, SeHarlan commented
Sorry @beekman but I think I'm gonna revert a couple commit cause I don't think it's helpful to combine the variable, helper and main css files. Let's talk tonight about what we wanna do with all the structural CSS spread about in the component files, I think that's more what I had in mind when talking about streamlining the CSS files

2020-10-08 02:25 UTC, beekman commented
@SeHarlan that's fine, I was just trying to follow your instructions to unify all the css into a single file, but I guess I misunderstood the to-do item on your checklist.

2020-10-08 02:38 UTC, SeHarlan commented
@beekman Sorry about that, I'll try to be clearer in the future. There are a bunch of other CSS files other than those four that I a little more concerned about tbh.

2020-10-08 02:58 UTC, SeHarlan commented
Commits reset and moved to css-clean-up branch and PR #382

2020-10-08 02:58 UTC, closed without merging