Css clean up
codeforpdx/dwellingly-app pull request #382
Opened 2020-10-08 02:56 UTC by SeHarlan

### What issue is this solving?
#343  in process
-button classes changed to Bulma classes. If we want to change the hover or active state of all buttons we can now do so from the variables.scss file.
-most colors are now variables (still need to comb through a little more)

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? I believe so, Bulma must be upgraded to 9.0
Any special requirements to test? not that I'm aware of

### Please make sure you've attempted to meet the following coding standards
- [ x] Code builds successfully
- [ x] Code has been tested and does not produce errors
- [ x] Code is readable and formatted
- [x ] There isn't any unnecessary commented-out code
- [x ] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

2020-10-12 23:54 UTC, Chris-Boe requested changes
A good step in the right direction!
There are merge conflicts that will have to be resolved.
I think you should turn off your auto-formatter when working with dwellingly, as when we have different people auto-formatting and committing the same file, it tends to go back and forth between people's opinionated styles 😄 Makes it a little hard to read in review sometimes but I'm glad Github added the "Hide whitespace changes" button

2020-10-14 04:00 UTC, SeHarlan commented
I resolved the merge conflicts but if someone can double check my work that'd make me feel a whole lot better :)
Should be fine Mostly I just gave preference to the development versions except where I added a few bulma classes

2020-10-14 04:06 UTC, beekman approved these changes, later dismissed
Looks good!

2020-10-18 03:43 UTC, Chris-Boe approved these changes

2020-10-18 03:46 UTC, merged