Change password payload
codeforpdx/dwellingly-app pull request #422
Opened 2020-11-11 17:42 UTC by Jam52

Payload changed to:
current_password
new_password
confirm_password

issue #418

The payload already contained the 3 fields as current, new, confirm

2020-11-12 03:17 UTC, NickSchimek requested changes
Thanks for looking into this. The payload needs to be updated to send all the form fields to the backend. I highlighted in the below comment where this can be done.

2020-11-12 03:17 UTC, NickSchimek commented on src/views/Settings/changePassword.js
> +        },
This is the payload that is being sent to the backend. 
Currently only the new_password is being sent. Please update to send all the form fields to the backend.

2020-11-12 19:51 UTC, Jam52 commented
Thanks Nick, I was concentrating too much on what the Formik elements were!

2020-11-13 11:32 UTC, NickSchimek approved these changes
Thanks @Jam52 - There were a bunch of style changes not related to this issue so I went ahead and removed them. I'm not sure what the style guidelines are for this repository, or even if there are any. However, I would prefer to only make the changes that are necessary. I also reverted the name changes, but kept the new payload params. Let me know if there are any questions. Thank you.

2020-11-13 11:35 UTC, NickSchimek commented
Verified manually. The request now sends the full payload. 

<img width="592" alt="Screen Shot 2020-11-13 at 8 26 36 PM" src="https://user-images.githubusercontent.com/19519317/99068257-7e38df80-25ef-11eb-90ba-3ab12b0bb3a9.png">

@Chris-Boe We have a PR in the backend that is pretty much ready to go if this looks good. If your OK with these changes then I will merge both this and backend one at the same time when they're ready to go.

2020-11-13 18:56 UTC, Jam52 commented
Thanks @NickSchimek I will ensure to check for a style guide and turn off / modify my extensions in future.

2020-11-16 09:10 UTC, merged