Backend to property managers
codeforpdx/dwellingly-app pull request #464
Opened 2020-12-06 15:20 UTC by dbridenbeck

### What issue is this solving?
closes #401 

### Any helpful knowledge/context for the reviewer?
1. I had to resolve merge conflicts over two occasions on this PR because life kept getting in the way for me to finish this PR, so a double check that those were properly merged would probably be wise.

2. Note how I implemented convertManagersDataForTable() on managers.js and how I'm rendering manager.status for the table. Not sure if that's really how we're hoping to implement this, but I gave it my best shot :)

3. Also note that my old laptop broke, I'm on a new one, and having trouble getting the backend up and running, so I'm unable to do any further testing until then, my apologies for the dumpster fire PR here :(

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code
- [x] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

2020-12-10 00:49 UTC, Chris-Boe requested changes
Nice job! Just a console log and unused file to get rid of, as well as some merge conflicts and this is ready to go!

2020-12-10 00:49 UTC, Chris-Boe commented on src/views/Settings/index.js
> +  console.log("data: ", data);
We can take out this console log

2020-12-10 00:49 UTC, Chris-Boe commented on src/views/Manager/index.js
> -import { PROPERTY_MANAGER_DATA } from "../pManagerData";
Let's delete the ptManagerData file if it's not being used anywhere anymore

2020-12-10 00:49 UTC, Chris-Boe commented on src/views/managers/managers.js
> +    if (manager.lastActive || !manager.archived) {
I think this is fine for now, but I will follow up with @htharker42 about what the statuses on the mockups actually mean. I also see "Awaiting Approval" but don't know how that differs from "Pending" nor how they get into those states

2020-12-10 15:28 UTC, darreniqgeo commented
Hey @Chris-Boe thanks again for the careful review! I resolved conflicts and pushed up the changes - I am still working to get the backend up working on my machine so I'm not able to check that everything is working correctly. . . if you have the chance to take a peek and validate things are working, that would be awesome, if not I'll try and get to that by this weekend!

If there are any other issues here please let me know and I'll get going on it this weekend :)

2020-12-12 18:49 UTC, Chris-Boe approved these changes
Thanks for getting this done! I know you're busy so I took the liberty of fixing up a couple small things to get this through.
Couple things on the PR:
 * Remember to still build the frontend so you know it compiles after making changes, there was a bad import that prevented the app from building
* Try to do only rebases and no merging from development or you'll get the ~30 extra duplicate commits from other people on this PR like you see in the list

2020-12-12 18:50 UTC, merged