477 -  Edits to a tenant info on the Manage Tenant screen should be saved
codeforpdx/dwellingly-app pull request #479
Opened 2020-12-14 05:10 UTC by pogorobot

### What issue is this solving?
#477

### Any helpful knowledge/context for the reviewer?
Is a `npm install` necessary? No
Any special requirements to test?  No

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code
- [x] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

If you're having trouble meeting this criteria, feel free to reach out on Slack for help!

2020-12-18 16:46 UTC, DaveTrost commented
@pogorobot - The code looks nice and clean! 

Please take a look at my responses to your comments here: #477.

2020-12-18 16:50 UTC, DaveTrost commented on src/views/Tenant/TenantView.js
> +            email: values.email
I believe this PUT request returns updated tenant data. I think it is best practice here to pull tenant values from that API response.

2021-01-07 02:11 UTC, Chris-Boe requested changes
On line 143 of src/views/Tenant/TenantView.js, we are trying to get the property related to the tenant, but that might not exist for some records, so we should update this to only send a request to /api/properties/{propertyId} when the tenant has that field

EDIT: I fixed this in a separate PR so we are getting the propertyID from the tenant's Lease object

2021-01-24 06:56 UTC, Chris-Boe approved these changes

2021-01-24 06:57 UTC, merged